# Generated by Django 5.1.2 on 2024-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name": "წიგნი",
                "verbose_name_plural": "წიგნები",
            },
        ),
    ]
